//CLIENTES
export const ADD_CLIENT = 'ADD_CLIENT';
export const ADD_CLIENT_SUCCESS = 'ADD_CLIENT_SUCCESS';
export const ADD_CLIENT_ERROR = 'ADD_CLIENT_ERROR';

export const GET_CLIENTS = 'GET_CLIENTS';
export const GET_CLIENTS_SUCCESS = 'GET_CLIENTS_SUCCESS';
export const GET_CLIENTS_ERROR = 'GET_CLIENTS_ERROR';

export const GET_CLIENT_DELETED = 'GET_CLIENT_DELETED';
export const DELETE_CLIENT_SUCCESS = 'DELETE_CLIENT_SUCCESS';
export const DELETE_CLIENT_ERROR = 'DELETE_CLIENT_ERROR';

export const GET_CLIENT_UPDATE = 'GET_CLIENT_UPDATE';
export const START_UPDATE_CLIENT = 'START_UPDATE_CLIENT';
export const UPDATE_CLIENT_SUCCESS = 'UPDATE_CLIENT_SUCCESS';
export const UPDATE_CLIENT_ERROR = 'UPDATE_CLIENT_ERROR';

//TURNOS

export const ADD_SHIFT = 'ADD_SHIFT';
export const ADD_SHIFT_SUCCESS = 'ADD_SHIFT_SUCCESS';
export const ADD_SHIFT_ERROR = 'ADD_SHIFT_ERROR';

export const GET_SHIFTS_BY_DATE = 'GET_SHIFTS_BY_DATE';
export const GET_SHIFTS_BY_DATE_SUCCESS = 'GET_SHIFTS_BY_DATE_SUCCESS';
export const GET_SHIFTS_BY_DATE_ERROR = 'GET_SHIFTS_BY_DATE_ERROR';

export const GET_SHIFT_DELETED = 'GET_SHIFT_DELETED';
export const DELETE_SHIFT_SUCCESS = 'DELETE_SHIFT_SUCCESS';
export const DELETE_SHIFT_ERROR = 'DELETE_SHIFT_ERROR';

export const GET_SHIFT_UPDATE = 'GET_SHIFT_UPDATE';
export const START_UPDATE_SHIFT = 'START_UPDATE_SHIFT';
export const UPDATE_SHIFT_SUCCESS = 'UPDATE_SHIFT_SUCCESS';
export const UPDATE_SHIFT_ERROR = 'UPDATE_SHIFT_ERROR';